# Site settings
title: Iran University of Science and Technology
course_name: College Orientation and Student Skills
course_description: This course attempts to introduce students to the Computer Enginering major, the Department of Computer Engineering at IUST and discuss skills necessary to excel and succeed as a stuent in this major.
course_semester: "Fall 2019"
description: |
    Instructor: Sauleh Eetemadi

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/co98" # the subpath of your site, e.g. /blog/
url: "http://sauleh.github.io/co98" # the base hostname & protocol for your site
syllabus: http://sauleh.github.io/co98/syllabus/
githubdir: 

# Author/user information
email: instructor-first-name@iust.ac.ir
twitter_username: sauleh_e 
github_username:  sauleh
authorurl: "http://sauleh.github.io"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
